import { test, expect } from './fixtures';
import { exportBackup, screenshotFullPage } from './workflow-helpers';

const storeId = 'official-54fb89ace317af63';
const storeName = 'GiGO中間';
const address = '福岡県中間市上蓮花寺3-1-1 1F・2F';

test('searches official stores and persists favorites, notes, and nullable personal machine counts', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'お店', exact: true }).click();
  await expect(page.getByRole('heading', { name: '設置店舗', exact: true })).toBeVisible();
  await expect(page.locator('.stores-source')).toContainText('全国1,370店舗');
  await expect(page.locator('.stores-source').getByRole('link', { name: '公式店舗一覧 ↗' })).toHaveAttribute('href', 'https://dcd.aikatsu.com/encore/pdf/shoplist.pdf');
  const prefecture = page.getByRole('combobox', { name: '都道府県' });
  await expect(prefecture.getByRole('option')).toHaveCount(48);
  await prefecture.selectOption('福岡県');
  await expect(page.locator('.stores-result')).toHaveText('54店舗 · 福岡県');
  await expect(page.locator('.store-card')).toHaveCount(50);
  await page.getByRole('button', { name: 'さらに50件表示（残り4店舗）', exact: true }).click();
  await expect(page.locator('.store-card')).toHaveCount(54);
  const search = page.getByRole('searchbox', { name: '店舗名・住所で検索' });
  await search.fill('ＧｉＧＯ中間');
  const store = page.locator('.store-card').filter({ has: page.getByRole('heading', { name: storeName, exact: true }) });
  await expect(page.locator('.store-card')).toHaveCount(1);
  await expect(store.locator('.store-count')).toHaveText('設置台数：未確認');
  await expect(store).toContainText(address);
  const map = new URL((await store.getByRole('link', { name: '地図 ↗' }).getAttribute('href'))!);
  expect(map.origin).toBe('https://www.google.com');
  expect(map.pathname).toBe('/maps/search/');
  expect(map.searchParams.get('query')).toBe(`${storeName} ${address}`);
  const route = new URL((await store.getByRole('link', { name: 'ルート ↗' }).getAttribute('href'))!);
  expect(route.pathname).toBe('/maps/dir/');
  expect(route.searchParams.get('destination')).toBe(`${storeName} ${address}`);
  await store.getByRole('button', { name: `${storeName}をお気に入りに登録`, exact: true }).click();
  await expect(store.getByRole('button', { name: `${storeName}をお気に入りから解除`, exact: true })).toHaveAttribute('aria-pressed', 'true');
  await store.getByRole('button', { name: '記録する', exact: true }).click();
  await store.getByRole('textbox', { name: 'メモ', exact: true }).fill('土曜は夕方に確認');
  await expect(store.getByRole('spinbutton', { name: '設置台数（未確認なら空欄）' })).toHaveValue('');
  await store.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(store.locator('.store-note')).toHaveText('土曜は夕方に確認');
  let backup = await exportBackup(page);
  expect(backup.storePreferences.find((item) => item.storeId === storeId)).toMatchObject({ favorite: true, note: '土曜は夕方に確認', machineCount: null });
  await page.reload();
  await page.getByRole('button', { name: 'お店', exact: true }).click();
  await page.getByRole('button', { name: '★ お気に入りのみ（1）', exact: true }).click();
  await expect(page.locator('.store-card')).toHaveCount(1);
  await expect(store.locator('.store-count')).toHaveText('設置台数：未確認');
  await expect(store.locator('.store-note')).toHaveText('土曜は夕方に確認');
  await store.getByRole('button', { name: '記録する', exact: true }).click();
  await store.getByRole('spinbutton', { name: '設置台数（未確認なら空欄）' }).fill('0');
  await store.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(store.locator('.store-count')).toHaveText('設置台数：0台（自分の記録）');
  backup = await exportBackup(page);
  expect(backup.storePreferences.find((item) => item.storeId === storeId)).toMatchObject({ favorite: true, note: '土曜は夕方に確認', machineCount: 0 });
  await page.reload();
  await page.getByRole('button', { name: 'お店', exact: true }).click();
  await page.getByRole('searchbox', { name: '店舗名・住所で検索' }).fill(storeName);
  await expect(store.locator('.store-count')).toHaveText('設置台数：0台（自分の記録）');
  await store.getByRole('button', { name: '記録する', exact: true }).click();
  await store.getByRole('spinbutton', { name: '設置台数（未確認なら空欄）' }).fill('1000');
  await store.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(store.getByRole('alert')).toContainText('台数は0〜999の整数');
  await expect(store.locator('.store-count')).toHaveText('設置台数：0台（自分の記録）');
  await page.setViewportSize({ width: 375, height: 812 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await screenshotFullPage(page, '/tmp/aikatsu-stores-mobile.png');
});
